"""DBN Standard (scoring rubric) routes."""

from fastapi import APIRouter, Depends, HTTPException, Response, status

from app.dependencies import get_scoring_service, get_standard_service
from app.schemas.dbn_standard import StandardCreate, StandardResponse
from app.services.dbn_standard_service import DBNStandardService
from app.services.scoring_service import ScoringService

router = APIRouter()


@router.get("", response_model=StandardResponse)
async def get_active_standard(
    scoring_service: ScoringService = Depends(get_scoring_service),
):
    """Return the currently active DBN scoring standard."""
    standard = await scoring_service.get_active_standard()
    if not standard:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No active standard")
    return StandardResponse.model_validate(standard)


@router.get("/download")
async def download_standard(
    scoring_service: ScoringService = Depends(get_scoring_service),
):
    """Download the active DBN Standard as a markdown template."""
    standard = await scoring_service.get_active_standard()
    if not standard:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No active standard")

    lines = [
        f"# {standard.name}",
        "",
        f"**Version:** {standard.version}",
        f"**Description:** {standard.description or 'N/A'}",
        "",
        "## Scoring Criteria",
        "",
        "| # | Criterion | Description | Weight | Max Score |",
        "|---|-----------|-------------|--------|-----------|",
    ]
    for criterion in standard.criteria:
        lines.append(
            f"| {criterion.sort_order} | {criterion.name} | "
            f"{criterion.description or ''} | {criterion.weight}% | {criterion.max_score} |"
        )

    lines.extend([
        "",
        "## How Scoring Works",
        "",
        "Each criterion is scored from 0 to the Max Score.",
        "The final score is calculated as the weighted average of all criteria.",
        "Scores are color-coded:",
        "  - **Green** (75-100): Strong / Excellent",
        "  - **Yellow** (50-74): Average, room for improvement",
        "  - **Red** (0-49): Needs significant improvement",
        "",
        "---",
        "*Generated by DBN Resume Reviewer*",
    ])

    content = "\n".join(lines)
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=dbn-standard.md"},
    )


@router.post("", response_model=StandardResponse, status_code=status.HTTP_201_CREATED)
async def create_standard(
    body: StandardCreate,
    standard_service: DBNStandardService = Depends(get_standard_service),
):
    """Create a new DBN scoring standard."""
    standard = await standard_service.create_standard(
        name=body.name,
        version=body.version,
        description=body.description,
    )
    return StandardResponse.model_validate(standard)
